[build]
  # Directory to publish (current directory since we have static files)
  publish = "."
  
  # No build command needed for static site
  command = ""

[build.environment]
  # Node.js version (if needed for future enhancements)
  NODE_VERSION = "18"

# Enable compression for all assets
[build.processing]
  skip_processing = false

[build.processing.css]
  bundle = true
  minify = true

[build.processing.js]
  bundle = true
  minify = true

[build.processing.html]
  pretty_urls = true

[build.processing.images]
  compress = true

# Redirect rules for SPA-like behavior
[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

# Redirect apex domain to www subdomain
[[redirects]]
  from = "https://caregrid.co.uk/*"
  to = "https://www.caregrid.co.uk/:splat"
  status = 301
  force = true

# Redirect HTTP to HTTPS
[[redirects]]
  from = "http://www.caregrid.co.uk/*"
  to = "https://www.caregrid.co.uk/:splat"
  status = 301
  force = true

# Custom headers for security and performance
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Content-Security-Policy = "default-src 'self'; style-src 'self' 'unsafe-inline' https://fonts.googleapis.com; font-src 'self' https://fonts.gstatic.com; img-src 'self' data:; script-src 'self' 'unsafe-inline';"
    # Enable compression
    Content-Encoding = "gzip, br"
    Vary = "Accept-Encoding"
    # Performance hints
    Accept-CH = "DPR, Viewport-Width, Width"

# Cache static assets with compression
[[headers]]
  for = "/css/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"
    Content-Encoding = "gzip, br"
    Vary = "Accept-Encoding"

[[headers]]
  for = "/js/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"
    Content-Encoding = "gzip, br"
    Vary = "Accept-Encoding"

[[headers]]
  for = "/images/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"
    Vary = "Accept-Encoding"

# Font caching
[[headers]]
  for = "*.woff2"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"
    Access-Control-Allow-Origin = "*"

[[headers]]
  for = "*.woff"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"
    Access-Control-Allow-Origin = "*"

# HTML caching
[[headers]]
  for = "*.html"
  [headers.values]
    Cache-Control = "public, max-age=3600"
    Content-Encoding = "gzip, br"
    Vary = "Accept-Encoding"

# 404 page
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 404