services:
  - type: web
    name: caregrid-backend
    env: node
    plan: free
    buildCommand: cd backend && npm install
    startCommand: cd backend && npm start
    healthCheckPath: /health
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: DATABASE_URL
        fromDatabase:
          name: caregrid-db
          property: connectionString
      - key: DB_HOST
        fromDatabase:
          name: caregrid-db
          property: host
      - key: DB_PORT
        fromDatabase:
          name: caregrid-db
          property: port
      - key: DB_NAME
        fromDatabase:
          name: caregrid-db
          property: database
      - key: DB_USER
        fromDatabase:
          name: caregrid-db
          property: user
      - key: DB_PASSWORD
        fromDatabase:
          name: caregrid-db
          property: password
      - key: JWT_SECRET
        generateValue: true
      - key: FRONTEND_URL
        value: https://www.caregrid.co.uk
      - key: CORS_ORIGIN
        value: https://www.caregrid.co.uk,https://caregrid.co.uk,http://localhost:3000,http://localhost:8000,http://localhost:8080,http://127.0.0.1:3000,http://127.0.0.1:8000,http://127.0.0.1:8080,https://caregrid2-ddk7.vercel.app,https://caregrid2.vercel.app
      - key: EMAIL_SERVICE
        value: gmail
      - key: EMAIL_USER
        value: noreply@caregriduk.co.uk
      - key: EMAIL_PASSWORD
        value: bycozcsxrffvvazo
      - key: EMAIL_FROM
        value: '"CareGrid UK" <noreply@caregriduk.co.uk>'

databases:
  - name: caregrid-db
    databaseName: caregrid
    plan: free
    postgresMajorVersion: 15